#! /bin/bash
#Väljastab mingi kujundi vastavalt kasutaja antud parameetritele

read -p "Sisesta ridade arv: " rida
read -p "Sisesta tärnide arv reas: " tarnid
if ! [[ "$rida" =~ ^-?[0-9]+$ ]]; then
    echo "Sisestatud väärtus ei ole arv."
    exit 1
fi

if ! [[ "$tarnid" =~ ^-?[0-9]+$ ]]; then
    echo "Sisestatud väärtus ei ole arv."
    exit 1
fi

for (( i=1; i<= rida; i++ )); do
	echo -n "$i."
	for (( n = 1; n <= $tarnid; n++ )); do
		echo -n "*"
	done
	echo ""
done
