#! /bin/bash
#Väljastab mingi kujundi vastavalt kasutaja antud parameetritele ja selles on auk

read -p "Sisesta ridade arv (1-200): " rida
read -p "Sisesta tärnide arv reas (1-200): " tarnid
if ! [[ "$rida" =~ ^-?[0-9]+$ ]]; then
    echo "Sisestatud väärtus ei ole arv."
    exit 1
fi

if (( rida > 200 )); then
    echo "Ridade arv ei tohi olla suurem kui 200."
    exit 1
fi

if ! [[ "$tarnid" =~ ^-?[0-9]+$ ]]; then
    echo "Sisestatud väärtus ei ole arv."
    exit 1
fi

if (( tarnid > 200 )); then
    echo "Tärnide arv ei tohi olla suurem kui 200."
    exit 1
fi

for (( i=1; i<=rida; i++ )); do
    echo -n "$i."
    if [[ $i -eq 1 || $i -eq $rida ]]; then
        for (( j=1; j<=tarnid; j++ )); do
            echo -n "*"
        done
    else
        echo -n "*"
        for (( j=2; j<tarnid; j++ )); do
            echo -n " "
        done
        if (( tarnid > 1 )); then
            echo -n "*"
        fi
    fi
    echo
done
