#!/bin/bash
# Skript, mis kuvab kujundi, kus igal real on o-d ja tärnid *,
# kus tärnide arv iga rea lõpus suureneb vastavalt rea numbrile.

read -p "Sisesta ridade arv: " rida
if ! [[ "$rida" =~ ^-?[0-9]+$ ]]; then
    echo "Sisestatud väärtus ei ole arv."
    exit 1
fi

for (( i=1; i<=rida; i++ )); do
	echo -n "$i."
    for (( j=1; j<=$((rida-i)); j++ )); do
        echo -n "o"
    done

    for (( j=1; j<=i; j++ )); do
        echo -n "*"
    done

    echo ""
done
