#! /bin/bash
# See skript võtab arvud 1-10 ja liidab ainult paaris arvud

summa=0
for arv in {1..10}; do
	if [ $((arv % 2)) -eq 0 ]; then
		summa=$(($summa + $arv))
		#echo $summa
	fi
done
echo "1-10 (kaasaarvatud) paarisarvude summa on: $summa"
