#! /bin/bash

read -p "Sisesta vanus: " vanus
if ! [[ "$vanus" =~ ^-?[0-9]+$ ]]; then
    echo "Vigane vanus"
    exit 1
fi

if  test $vanus -gt 0 -a $vanus -lt 11; then
	echo "Sa oled laps."
elif test $vanus -ge 11 -a $vanus -lt 18; then
	echo "Sa oled nooruk."
elif test $vanus -ge 18 -a $vanus -lt 63; then
	echo "Sa oled täiskasvanu."
elif test $vanus -ge 63 -a $vanus -lt 120; then
	echo "Sa oled senioor."
else
	echo "Sa ei ole osa enam sellest maailmast või oled fictional tegelane"
fi
