#! /bin/bash

# See skirpt väljastab hetke kellaaja kuupäeva ja kuu kalendri

today_date="$(date +"Today is %A, %B %d, %Y")"
time_rn="$(date +"Time is %H:%M")"
year_calendar="$(date +"Calendar of %B %Y")"
calendar=$(cal | tail -n 7)

echo "$today_date"
echo "$time_rn"

echo "$year_calendar"
echo "$calendar"
