#! /bin/bash
# See skript võtab kasutaja arvu ja ütleb kas see on paaris või paaritu

echo -n "Sisesta täisarv: "
read arv

if [ $((arv % 2)) -eq 0 ]; then
	echo "$arv on paaris."

else
	echo "$arv on paaritu."
fi
